### Preamble

In [341]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [342]:
import pandas as pd
import os
%cd /home/jeroen/repos/traffic-scheduling/single
os.makedirs("results/cache", exist_ok=True)
os.makedirs("results/figures", exist_ok=True)

/home/jeroen/repos/traffic-scheduling/single

## Specify experiments

In [343]:
from single.ppo import PpoRl
from single.threshold import ThresholdGridSearch
from single.imitation import ImitationLearning
from single.basics import bimodal_exponential, generate_instance
import numpy as np
import time
from datetime import datetime
import os

Specify "ingredients": distributions and scheduling models (i.e., procedures that train/eval).
Specify experiments by combining these "ingredients". When the train distribution differs from the eval distribution, we are effectively measuring how well the model generalizes.

In [344]:
# global number of test instances used in model evaluation
N_test = 10
timelimit_test = 120 # two minutes

# model classes, possibly parameterized
models = {
    'Grid':        ThresholdGridSearch(tau_range=np.linspace(0, 1, 20)),
    'PPO':         PpoRl(steps=500_000, max_k=5, verbose=0),
    'Imitation':   ImitationLearning(max_k=5),
}

# some fixed gap distributions
gap_distributions = {
    # these have the same arrival intensity, # computed using s2 = (mu - p*s1) / (1 - p)
    'high': bimodal_exponential(p=0.5, s1=0.1, s2=10.00),
    'low':  bimodal_exponential(p=0.1, s1=0.1, s2= 5.6),
}

# definition of experiments (measure generalization by providing different test (n, F) pair)
exps = [
    ([20, 20], 'low', 'Imitation', [20, 20], 'low'),
    ([20, 20], 'high', 'Imitation', [20, 20], 'high'),
    ([20, 20], 'low', 'Grid', [20, 20], 'low'),
    ([20, 20], 'high', 'Grid', [20, 20], 'high'),
    ([20, 20], 'low', 'PPO', [20, 20], 'low'),
    ([20, 20], 'high', 'PPO', [20, 20], 'high'),

    ([40, 40], 'low', 'Imitation',  [40, 40], 'low'),
    ([40, 40], 'high', 'Imitation', [40, 40], 'high'),
    ([40, 40], 'low', 'Grid',       [40, 40], 'low'),
    ([40, 40], 'high', 'Grid',      [40, 40], 'high'),
    ([40, 40], 'low', 'PPO',        [40, 40], 'low'),
    ([40, 40], 'high', 'PPO',       [40, 40], 'high'),

    ([60, 60], 'low', 'Imitation',  [60, 60], 'low'),
    ([60, 60], 'high', 'Imitation', [60, 60], 'high'),
    ([60, 60], 'low', 'Grid',       [60, 60], 'low'),
    ([60, 60], 'high', 'Grid',      [60, 60], 'high'),
    ([60, 60], 'low', 'PPO',        [60, 60], 'low'),
    ([60, 60], 'high', 'PPO',       [60, 60], 'high'),

    ([20, 20, 20], 'low', 'Imitation',  [20, 20, 20], 'low'),
    ([20, 20, 20], 'high', 'Imitation', [20, 20, 20], 'high'),
    ([20, 20, 20], 'low', 'Grid',       [20, 20, 20], 'low'),
    ([20, 20, 20], 'high', 'Grid',      [20, 20, 20], 'high'),
    ([20, 20, 20], 'low', 'PPO',        [20, 20, 20], 'low'),
    ([20, 20, 20], 'high', 'PPO',       [20, 20, 20], 'high'),

    ([40, 40, 40], 'low', 'Imitation',  [40, 40, 40], 'low'),
    ([40, 40, 40], 'high', 'Imitation', [40, 40, 40], 'high'),
    ([40, 40, 40], 'low', 'Grid',       [40, 40, 40], 'low'),
    ([40, 40, 40], 'high', 'Grid',      [40, 40, 40], 'high'),
    ([40, 40, 40], 'low', 'PPO',        [40, 40, 40], 'low'),
    ([40, 40, 40], 'high', 'PPO',       [40, 40, 40], 'high'),
]

Next, we "compile" these textual experiment specifications:
 - add explicit generator function based on the textual specification,
 - instantiate each model class (optionally with parameters).

In [345]:
experiments = pd.DataFrame(exps, columns=['n_train', 'F_train', 'model_spec', 'n_test', 'F_test'])

for i, row in experiments.iterrows():
    for m in ['train', 'test']:
        n = row[f'n_{m}']; F = row[f'F_{m}']
        # when F is not a list, broadcast according to number of routes
        if isinstance(F, str): 
            F = [F]*len(n)
            row[f'F_{m}'] = F # write broadcasted list back
        F = [gap_distributions[f] for f in F]
        experiments.loc[i, f'gen_{m}'] = lambda F=F.copy(), n=n.copy(): generate_instance(F, n=n)
        experiments.loc[i, f'gen_{m}_name'] = '_'.join(str(s) for s in row[f'n_{m}']) + '_' + '_'.join(row[f'F_{m}'])
    experiments.loc[i, f'name'] = experiments.loc[i, 'gen_train_name'] + '_' + experiments.loc[i, 'model_spec'] + '_' + experiments.loc[i, 'gen_train_name']

# look up model by name, put in pandas table
experiments['model'] = experiments.apply(lambda row: models[row['model_spec']], axis=1)

experiments.drop(columns=['gen_train', 'gen_test', 'model'])

,n_train,F_train,model_spec,n_test,F_test,gen_train_name,gen_test_name,name
0,"[20, 20]","[low, low]",Imitation,"[20, 20]","[low, low]",20_20_low_low,20_20_low_low,20_20_low_low_Imitation_20_20_low_low
1,"[20, 20]","[high, high]",Imitation,"[20, 20]","[high, high]",20_20_high_high,20_20_high_high,20_20_high_high_Imitation_20_20_high_high
2,"[20, 20]","[low, low]",Grid,"[20, 20]","[low, low]",20_20_low_low,20_20_low_low,20_20_low_low_Grid_20_20_low_low
3,"[20, 20]","[high, high]",Grid,"[20, 20]","[high, high]",20_20_high_high,20_20_high_high,20_20_high_high_Grid_20_20_high_high
4,"[20, 20]","[low, low]",PPO,"[20, 20]","[low, low]",20_20_low_low,20_20_low_low,20_20_low_low_PPO_20_20_low_low
5,"[20, 20]","[high, high]",PPO,"[20, 20]","[high, high]",20_20_high_high,20_20_high_high,20_20_high_high_PPO_20_20_high_high
6,"[40, 40]","[low, low]",Imitation,"[40, 40]","[low, low]",40_40_low_low,40_40_low_low,40_40_low_low_Imitation_40_40_low_low
7,"[40, 40]","[high, high]",Imitation,"[40, 40]","[high, high]",40_40_high_high,40_40_high_high,40_40_high_high_Imitation_40_40_high_high
8,"[40, 40]","[low, low]",Grid,"[40, 40]","[low, low]",40_40_low_low,40_40_low_low,40_40_low_low_Grid_40_40_low_low
9,"[40, 40]","[high, high]",Grid,"[40, 40]","[high, high]",40_40_high_high,40_40_high_high,40_40_high_high_Grid_40_40_high_high
10,"[40, 40]","[low, low]",PPO,"[40, 40]","[low, low]",40_40_low_low,40_40_low_low,40_40_low_low_PPO_40_40_low_low
11,"[40, 40]","[high, high]",PPO,"[40, 40]","[high, high]",40_40_high_high,40_40_high_high,40_40_high_high_PPO_40_40_high_high
12,"[60, 60]","[low, low]",Imitation,"[60, 60]","[low, low]",60_60_low_low,60_60_low_low,60_60_low_low_Imitation_60_60_low_low
13,"[60, 60]","[high, high]",Imitation,"[60, 60]","[high, high]",60_60_high_high,60_60_high_high,60_60_high_high_Imitation_60_60_high_high
14,"[60, 60]","[low, low]",Grid,"[60, 60]","[low, low]",60_60_low_low,60_60_low_low,60_60_low_low_Grid_60_60_low_low
15,"[60, 60]","[high, high]",Grid,"[60, 60]","[high, high]",60_60_high_high,60_60_high_high,60_60_high_high_Grid_60_60_high_high
16,"[60, 60]","[low, low]",PPO,"[60, 60]","[low, low]",60_60_low_low,60_60_low_low,60_60_low_low_PPO_60_60_low_low
17,"[60, 60]","[high, high]",PPO,"[60, 60]","[high, high]",60_60_high_high,60_60_high_high,60_60_high_high_PPO_60_60_high_high
18,"[20, 20, 20]","[low, low, low]",Imitation,"[20, 20, 20]","[low, low, low]",20_20_20_low_low_low,20_20_20_low_low_low,20_20_20_low_low_low_Imitation_20_20_20_low_lo...
19,"[20, 20, 20]","[high, high, high]",Imitation,"[20, 20, 20]","[high, high, high]",20_20_20_high_high_high,20_20_20_high_high_high,20_20_20_high_high_high_Imitation_20_20_20_hig...
20,"[20, 20, 20]","[low, low, low]",Grid,"[20, 20, 20]","[low, low, low]",20_20_20_low_low_low,20_20_20_low_low_low,20_20_20_low_low_low_Grid_20_20_20_low_low_low
21,"[20, 20, 20]","[high, high, high]",Grid,"[20, 20, 20]","[high, high, high]",20_20_20_high_high_high,20_20_20_high_high_high,20_20_20_high_high_high_Grid_20_20_20_high_hig...
22,"[20, 20, 20]","[low, low, low]",PPO,"[20, 20, 20]","[low, low, low]",20_20_20_low_low_low,20_20_20_low_low_low,20_20_20_low_low_low_PPO_20_20_20_low_low_low
23,"[20, 20, 20]","[high, high, high]",PPO,"[20, 20, 20]","[high, high, high]",20_20_20_high_high_high,20_20_20_high_high_high,20_20_20_high_high_high_PPO_20_20_20_high_high...
24,"[40, 40, 40]","[low, low, low]",Imitation,"[40, 40, 40]","[low, low, low]",40_40_40_low_low_low,40_40_40_low_low_low,40_40_40_low_low_low_Imitation_40_40_40_low_lo...
25,"[40, 40, 40]","[high, high, high]",Imitation,"[40, 40, 40]","[high, high, high]",40_40_40_high_high_high,40_40_40_high_high_high,40_40_40_high_high_high_Imitation_40_40_40_hig...
26,"[40, 40, 40]","[low, low, low]",Grid,"[40, 40, 40]","[low, low, low]",40_40_40_low_low_low,40_40_40_low_low_low,40_40_40_low_low_low_Grid_40_40_40_low_low_low
27,"[40, 40, 40]","[high, high, high]",Grid,"[40, 40, 40]","[high, high, high]",40_40_40_high_high_high,40_40_40_high_high_high,40_40_40_high_high_high_Grid_40_40_40_high_hig...
28,"[40, 40, 40]","[low, low, low]",PPO,"[40, 40, 40]","[low, low, low]",40_40_40_low_low_low,40_40_40_low_low_low,40_40_40_low_low_low_PPO_40_40_40_low_low_low
29,"[40, 40, 40]","[high, high, high]",PPO,"[40, 40, 40]","[high, high, high]",40_40_40_high_high_high,40_40_40_high_high_high,40_40_40_high_high_high_PPO_40_40_40_high_high...

## Run all experiments

In [346]:
import pickle
from pathlib import Path

def gen_test_data_and_optimal_solutions(gen, name):
    filename = f"results/cache/test-schedules-{name}.pkl"
    path = Path(filename)
    if path.is_file():
        with open(filename, "rb") as f:
            instances, time_opt = pickle.load(f)
        print("Loading test data from cache")
    else:
        print('Generating test data (and computing optimal schedules)')
        instances = [gen() for _ in range(N_test)]
        start_time = time.time()
        for s in instances:
            s.solve(timelimit=timelimit_test, cutting_planes=[2, 3])
        time_opt = time.time() - start_time
        print('Done MILP solving')

        with open(filename, "wb") as file:
            pickle.dump([instances, time_opt], file)

    return instances, time_opt

In [347]:
for i, exp in experiments.iterrows():
    print(f"Experiment {i}: {exp['n_train']}, {exp['F_train']}"
          f" -> {exp['model_spec']} -> {exp['n_test']}, {exp['F_test']}")

    # create test instances and solve them to optimality
    test_instances, time_opt = gen_test_data_and_optimal_solutions(exp['gen_test'], exp['gen_test_name'])

    # ref to instantiated model
    model = exp['model']

    # train model
    start_time = time.time()
    model.train(exp['gen_train'], name=exp['name'])
    time_train = time.time() - start_time

    if hasattr(model, 'report'):
        model.report(exp['name'])

    # evaluate model
    obj = 0
    start_time = time.time()
    for s in test_instances:
        obj += model.eval(s)
    obj = obj / len(test_instances)
    time_test = time.time() - start_time
    
    opt = sum([t.opt.delay for t in test_instances]) / len(test_instances)
    experiments.loc[i, 'opt'] = opt
    experiments.loc[i, 'obj'] = obj
    experiments.loc[i, 'gap'] = 100 * ((obj / opt) - 1)
    experiments.loc[i, 'time_opt'] = time_opt
    experiments.loc[i, 'time_train'] = time_train
    experiments.loc[i, 'time_test'] = time_test

now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
print(f"Done at: {now}")
os.system('notify-send "traffic-scheduling" "Experiments done"')

Experiment 0: [20, 20], ['low', 'low'] -> Imitation -> [20, 20], ['low', 'low']
Loading test data from cache
Loading expert demonstration from cache

Experiment 1: [20, 20], ['high', 'high'] -> Imitation -> [20, 20], ['high', 'high']
Loading test data from cache
Loading expert demonstration from cache

Experiment 2: [20, 20], ['low', 'low'] -> Grid -> [20, 20], ['low', 'low']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00
Experiment 3: [20, 20], ['high', 'high'] -> Grid -> [20, 20], ['high', 'high']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00

/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 4: [20, 20], ['low', 'low'] -> PPO -> [20, 20], ['low', 'low']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:27<00:00, 3393.89step/s]
/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 5: [20, 20], ['high', 'high'] -> PPO -> [20, 20], ['high', 'high']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:27<00:00, 3394.25step/s]

Experiment 6: [40, 40], ['low', 'low'] -> Imitation -> [40, 40], ['low', 'low']
Loading test data from cache

Generating expert demonstration: 100%|██████████| 20/20 [00:02<00:00,  8.89it/s]

Experiment 7: [40, 40], ['high', 'high'] -> Imitation -> [40, 40], ['high', 'high']
Loading test data from cache

Generating expert demonstration: 100%|██████████| 20/20 [00:13<00:00,  1.54it/s]

Experiment 8: [40, 40], ['low', 'low'] -> Grid -> [40, 40], ['low', 'low']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00
Experiment 9: [40, 40], ['high', 'high'] -> Grid -> [40, 40], ['high', 'high']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00

/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 10: [40, 40], ['low', 'low'] -> PPO -> [40, 40], ['low', 'low']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:27<00:00, 3391.36step/s]
/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 11: [40, 40], ['high', 'high'] -> PPO -> [40, 40], ['high', 'high']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:26<00:00, 3414.97step/s]

Experiment 12: [60, 60], ['low', 'low'] -> Imitation -> [60, 60], ['low', 'low']
Loading test data from cache

Generating expert demonstration: 100%|██████████| 20/20 [00:05<00:00,  3.66it/s]

Experiment 13: [60, 60], ['high', 'high'] -> Imitation -> [60, 60], ['high', 'high']
Loading test data from cache

Generating expert demonstration: 100%|██████████| 20/20 [00:28<00:00,  1.41s/it]

Experiment 14: [60, 60], ['low', 'low'] -> Grid -> [60, 60], ['low', 'low']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00
Experiment 15: [60, 60], ['high', 'high'] -> Grid -> [60, 60], ['high', 'high']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00

/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 16: [60, 60], ['low', 'low'] -> PPO -> [60, 60], ['low', 'low']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:27<00:00, 3384.48step/s]
/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 17: [60, 60], ['high', 'high'] -> PPO -> [60, 60], ['high', 'high']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:28<00:00, 3371.17step/s]

Experiment 18: [20, 20, 20], ['low', 'low', 'low'] -> Imitation -> [20, 20, 20], ['low', 'low', 'low']
Loading test data from cache

Generating expert demonstration: 100%|██████████| 20/20 [02:35<00:00,  7.80s/it]

Experiment 19: [20, 20, 20], ['high', 'high', 'high'] -> Imitation -> [20, 20, 20], ['high', 'high', 'high']
Loading test data from cache

Generating expert demonstration: 100%|██████████| 20/20 [03:08<00:00,  9.43s/it]

Experiment 20: [20, 20, 20], ['low', 'low', 'low'] -> Grid -> [20, 20, 20], ['low', 'low', 'low']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00
Experiment 21: [20, 20, 20], ['high', 'high', 'high'] -> Grid -> [20, 20, 20], ['high', 'high', 'high']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00

/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 22: [20, 20, 20], ['low', 'low', 'low'] -> PPO -> [20, 20, 20], ['low', 'low', 'low']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:30<00:00, 3332.15step/s]
/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 23: [20, 20, 20], ['high', 'high', 'high'] -> PPO -> [20, 20, 20], ['high', 'high', 'high']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:30<00:00, 3328.48step/s]

Experiment 24: [40, 40, 40], ['low', 'low', 'low'] -> Imitation -> [40, 40, 40], ['low', 'low', 'low']
Generating test data (and computing optimal schedules)
Done MILP solving

Generating expert demonstration: 100%|██████████| 20/20 [08:31<00:00, 25.59s/it]

Experiment 25: [40, 40, 40], ['high', 'high', 'high'] -> Imitation -> [40, 40, 40], ['high', 'high', 'high']
Generating test data (and computing optimal schedules)
Done MILP solving

Generating expert demonstration: 100%|██████████| 20/20 [15:37<00:00, 46.86s/it]

Experiment 26: [40, 40, 40], ['low', 'low', 'low'] -> Grid -> [40, 40, 40], ['low', 'low', 'low']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00
Experiment 27: [40, 40, 40], ['high', 'high', 'high'] -> Grid -> [40, 40, 40], ['high', 'high', 'high']
Loading test data from cache
searching tau over 0.00, 0.05, 0.11, 0.16, 0.21, 0.26, 0.32, 0.37, 0.42, 0.47, 0.53, 0.58, 0.63, 0.68, 0.74, 0.79, 0.84, 0.89, 0.95, 1.00

/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 28: [40, 40, 40], ['low', 'low', 'low'] -> PPO -> [40, 40, 40], ['low', 'low', 'low']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:27<00:00, 3386.68step/s]
/home/jeroen/.local/share/miniforge3/envs/traffic/lib/python3.12/site-packages/stable_baselines3/common/vec_env/vec_monitor.py:44: UserWarning: The environment is already wrapped with a `Monitor` wrapperbut you are wrapping it with a `VecMonitor` wrapper, the `Monitor` statistics will beoverwritten by the `VecMonitor` ones.
  warnings.warn(

Experiment 29: [40, 40, 40], ['high', 'high', 'high'] -> PPO -> [40, 40, 40], ['high', 'high', 'high']
Loading test data from cache

Training: 100%|██████████| 500000/500000 [02:27<00:00, 3393.67step/s]

Done at: 2025-11-03 01:48:52

0

## Generate results table

In [348]:
results = experiments.drop(columns=['gen_train', 'gen_test', 'model'])

# convert lists of strings like ['low', 'low'] into actual string '[low, low]'
for i, row in results.iterrows():
    for col in ['n_train', 'F_train', 'n_test', 'F_test']:
        results.loc[i, col] = r'\texttt{[' + ', '.join(str(i) for i in row[col]) + r']}'

# general precaution: replace underscores with spaces to avoid latex errors
results.columns = results.columns.str.replace('_', ' ')

results

,n train,F train,model spec,n test,F test,gen train name,gen test name,name,opt,obj,gap,time opt,time train,time test
0,"\texttt{[20, 20]}","\texttt{[low, low]}",Imitation,"\texttt{[20, 20]}","\texttt{[low, low]}",20_20_low_low,20_20_low_low,20_20_low_low_Imitation_20_20_low_low,12.538185,12.857279,2.544983,0.494449,10.794131,0.093892
1,"\texttt{[20, 20]}","\texttt{[high, high]}",Imitation,"\texttt{[20, 20]}","\texttt{[high, high]}",20_20_high_high,20_20_high_high,20_20_high_high_Imitation_20_20_high_high,14.106125,14.693492,4.163919,0.482333,10.303269,0.094536
2,"\texttt{[20, 20]}","\texttt{[low, low]}",Grid,"\texttt{[20, 20]}","\texttt{[low, low]}",20_20_low_low,20_20_low_low,20_20_low_low_Grid_20_20_low_low,12.538185,12.899862,2.884604,0.494449,6.528680,0.006651
3,"\texttt{[20, 20]}","\texttt{[high, high]}",Grid,"\texttt{[20, 20]}","\texttt{[high, high]}",20_20_high_high,20_20_high_high,20_20_high_high_Grid_20_20_high_high,14.106125,14.302608,1.392894,0.482333,6.367270,0.006574
4,"\texttt{[20, 20]}","\texttt{[low, low]}",PPO,"\texttt{[20, 20]}","\texttt{[low, low]}",20_20_low_low,20_20_low_low,20_20_low_low_PPO_20_20_low_low,12.538185,13.179568,5.115436,0.494449,147.328267,0.085923
5,"\texttt{[20, 20]}","\texttt{[high, high]}",PPO,"\texttt{[20, 20]}","\texttt{[high, high]}",20_20_high_high,20_20_high_high,20_20_high_high_PPO_20_20_high_high,14.106125,14.793097,4.870032,0.482333,147.312099,0.084099
6,"\texttt{[40, 40]}","\texttt{[low, low]}",Imitation,"\texttt{[40, 40]}","\texttt{[low, low]}",40_40_low_low,40_40_low_low,40_40_low_low_Imitation_40_40_low_low,27.407008,27.594446,0.683903,4.022383,13.358776,0.190348
7,"\texttt{[40, 40]}","\texttt{[high, high]}",Imitation,"\texttt{[40, 40]}","\texttt{[high, high]}",40_40_high_high,40_40_high_high,40_40_high_high_Imitation_40_40_high_high,39.741625,40.953340,3.048982,3.591624,24.115678,0.186230
8,"\texttt{[40, 40]}","\texttt{[low, low]}",Grid,"\texttt{[40, 40]}","\texttt{[low, low]}",40_40_low_low,40_40_low_low,40_40_low_low_Grid_40_40_low_low,27.407008,27.580523,0.633102,4.022383,11.936231,0.012103
9,"\texttt{[40, 40]}","\texttt{[high, high]}",Grid,"\texttt{[40, 40]}","\texttt{[high, high]}",40_40_high_high,40_40_high_high,40_40_high_high_Grid_40_40_high_high,39.741625,40.501097,1.911024,3.591624,11.753293,0.011849
10,"\texttt{[40, 40]}","\texttt{[low, low]}",PPO,"\texttt{[40, 40]}","\texttt{[low, low]}",40_40_low_low,40_40_low_low,40_40_low_low_PPO_40_40_low_low,27.407008,28.468205,3.871989,4.022383,147.438332,0.163920
11,"\texttt{[40, 40]}","\texttt{[high, high]}",PPO,"\texttt{[40, 40]}","\texttt{[high, high]}",40_40_high_high,40_40_high_high,40_40_high_high_PPO_40_40_high_high,39.741625,42.366348,6.604469,3.591624,146.418300,0.163436
12,"\texttt{[60, 60]}","\texttt{[low, low]}",Imitation,"\texttt{[60, 60]}","\texttt{[low, low]}",60_60_low_low,60_60_low_low,60_60_low_low_Imitation_60_60_low_low,40.080570,40.520182,1.096821,5.594582,16.987021,0.292378
13,"\texttt{[60, 60]}","\texttt{[high, high]}",Imitation,"\texttt{[60, 60]}","\texttt{[high, high]}",60_60_high_high,60_60_high_high,60_60_high_high_Imitation_60_60_high_high,60.530365,61.145466,1.016186,9.442301,39.432054,0.280934
14,"\texttt{[60, 60]}","\texttt{[low, low]}",Grid,"\texttt{[60, 60]}","\texttt{[low, low]}",60_60_low_low,60_60_low_low,60_60_low_low_Grid_60_60_low_low,40.080570,40.744641,1.656842,5.594582,18.033775,0.018226
15,"\texttt{[60, 60]}","\texttt{[high, high]}",Grid,"\texttt{[60, 60]}","\texttt{[high, high]}",60_60_high_high,60_60_high_high,60_60_high_high_Grid_60_60_high_high,60.530365,60.716127,0.306890,9.442301,17.764387,0.017850
16,"\texttt{[60, 60]}","\texttt{[low, low]}",PPO,"\texttt{[60, 60]}","\texttt{[low, low]}",60_60_low_low,60_60_low_low,60_60_low_low_PPO_60_60_low_low,40.080570,41.916108,4.579620,5.594582,147.738389,0.241954
17,"\texttt{[60, 60]}","\texttt{[high, high]}",PPO,"\texttt{[60, 60]}","\texttt{[high, high]}",60_60_high_high,60_60_high_high,60_60_high_high_PPO_60_60_high_high,60.530365,63.889047,5.548755,9.442301,148.321400,0.254449
18,"\texttt{[20, 20, 20]}","\texttt{[low, low, low]}",Imitation,"\texttt{[20, 20, 20]}","\texttt{[low, low, low]}",20_20_20_low_low_low,20_20_20_low_low_low,20_20_20_low_low_low_Imitation_20_20_20_low_lo...,57.476883,341.072574,493.408266,18.652781,166.979335,0.144329
19,"\texttt{[20, 20, 20]}","\texttt{[high, high, high]}",Imitation,"\texttt{[20, 20, 20]}","\texttt{[high, high, high]}",20_20_20_high_high_high,20_20_20_high_high_high,20_20_20_high_high_high_Imitation_20_20_20_hig...,80.342063,383.486959,377.317792,11.573517,199.548570,0.145442
20,"\texttt{[20, 20, 20]}","\texttt{[low, low, low]}",Grid,"\texttt{[20, 20, 20]}","\texttt{[low, low, low]}",20_20_20_low_low_low,20_20_20_low_low_low,20_20_20_low_low_low_Grid_20_20_20_low_low_low,57.476883,63.675464,10.784477,18.652781,10.956625,0.011519
21,"\texttt{[20, 20, 20]}","\texttt{[high, high, high]}",Grid,"\texttt{[20, 20, 20]}","\texttt{[high, high, high]}",20_20_20_high_high_high,20_20_20_high_high_high,20_20_20_high_high_high_Grid_20_20_20_high_hig...,80.342063,82.451770,2.625906,11.573517,10.584291,0.010753
22,"\texttt{[20, 20, 20]}","\texttt{[low, low, low]}",PPO,"\texttt{[20, 20, 20]}","\texttt{[low, low, low]}",20_20_20_low_low_low,20_20_20_low_low_low,20_20_20_low_low_low_PPO_20_20_20_low_low_low,57.476883,75.491915,31.343091,18.652781,150.058838,0.125922
23,"\texttt{[20, 20, 20]}","\texttt{[high, high, high]}",PPO,"\texttt{[20, 20, 20]}","\texttt{[high, high, high]}",20_20_20_high_high_high,20_20_20_high_high_high,20_20_20_high_high_high_PPO_20_20_20_high_high...,80.342063,118.609136,47.630185,11.573517,150.223690,0.128207
24,"\texttt{[40, 40, 40]}","\texttt{[low, low, low]}",Imitation,"\texttt{[40, 40, 40]}","\texttt{[low, low, low]}",40_40_40_low_low_low,40_40_40_low_low_low,40_40_40_low_low_low_Imitation_40_40_40_low_lo...,127.669176,707.970055,454.534836,316.696654,523.053128,0.284361
25,"\texttt{[40, 40, 40]}","\texttt{[high, high, high]}",Imitation,"\texttt{[40, 40, 40]}","\texttt{[high, high, high]}",40_40_40_high_high_high,40_40_40_high_high_high,40_40_40_high_high_high_Imitation_40_40_40_hig...,207.811888,1256.956556,504.853057,307.539822,948.414813,0.284621
26,"\texttt{[40, 40, 40]}","\texttt{[low, low, low]}",Grid,"\texttt{[40, 40, 40]}","\texttt{[low, low, low]}",40_40_40_low_low_low,40_40_40_low_low_low,40_40_40_low_low_low_Grid_40_40_40_low_low_low,127.669176,137.606760,7.783855,316.696654,21.516230,0.021668
27,"\texttt{[40, 40, 40]}","\texttt{[high, high, high]}",Grid,"\texttt{[40, 40, 40]}","\texttt{[high, high, high]}",40_40_40_high_high_high,40_40_40_high_high_high,40_40_40_high_high_high_Grid_40_40_40_high_hig...,207.811888,220.589856,6.148815,307.539822,20.403130,0.020546
28,"\texttt{[40, 40, 40]}","\texttt{[low, low, low]}",PPO,"\texttt{[40, 40, 40]}","\texttt{[low, low, low]}",40_40_40_low_low_low,40_40_40_low_low_low,40_40_40_low_low_low_PPO_40_40_40_low_low_low,127.669176,222.078030,73.948040,316.696654,147.643010,0.248778
29,"\texttt{[40, 40, 40]}","\texttt{[high, high, high]}",PPO,"\texttt{[40, 40, 40]}","\texttt{[high, high, high]}",40_40_40_high_high_high,40_40_40_high_high_high,40_40_40_high_high_high_PPO_40_40_40_high_high...,207.811888,430.904077,107.352949,307.539822,147.338457,0.248133

In [349]:
# pivot
results = results.pivot_table(
    index=['n train', 'F train'],   # rows
    columns='model spec',           # columns
    values=['opt', 'time opt', 'obj', 'gap', 'time train'],  # metrics per method
    sort=False
)
results

                                                          opt              \
model spec                                          Imitation        Grid
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           12.538185   12.538185
                      \texttt{[high, high]}         14.106125   14.106125
\texttt{[40, 40]}     \texttt{[low, low]}           27.407008   27.407008
                      \texttt{[high, high]}         39.741625   39.741625
\texttt{[60, 60]}     \texttt{[low, low]}           40.080570   40.080570
                      \texttt{[high, high]}         60.530365   60.530365
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      57.476883   57.476883
                      \texttt{[high, high, high]}   80.342063   80.342063
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     127.669176  127.669176
                      \texttt{[high, high, high]}  207.811888  207.811888

                                                                 time opt  \
model spec                                                PPO   Imitation
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           12.538185    0.494449
                      \texttt{[high, high]}         14.106125    0.482333
\texttt{[40, 40]}     \texttt{[low, low]}           27.407008    4.022383
                      \texttt{[high, high]}         39.741625    3.591624
\texttt{[60, 60]}     \texttt{[low, low]}           40.080570    5.594582
                      \texttt{[high, high]}         60.530365    9.442301
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      57.476883   18.652781
                      \texttt{[high, high, high]}   80.342063   11.573517
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     127.669176  316.696654
                      \texttt{[high, high, high]}  207.811888  307.539822

                                                                           \
model spec                                               Grid         PPO
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}            0.494449    0.494449
                      \texttt{[high, high]}          0.482333    0.482333
\texttt{[40, 40]}     \texttt{[low, low]}            4.022383    4.022383
                      \texttt{[high, high]}          3.591624    3.591624
\texttt{[60, 60]}     \texttt{[low, low]}            5.594582    5.594582
                      \texttt{[high, high]}          9.442301    9.442301
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      18.652781   18.652781
                      \texttt{[high, high, high]}   11.573517   11.573517
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     316.696654  316.696654
                      \texttt{[high, high, high]}  307.539822  307.539822

                                                           obj              \
model spec                                           Imitation        Grid
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}            12.857279   12.899862
                      \texttt{[high, high]}          14.693492   14.302608
\texttt{[40, 40]}     \texttt{[low, low]}            27.594446   27.580523
                      \texttt{[high, high]}          40.953340   40.501097
\texttt{[60, 60]}     \texttt{[low, low]}            40.520182   40.744641
                      \texttt{[high, high]}          61.145466   60.716127
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      341.072574   63.675464
                      \texttt{[high, high, high]}   383.486959   82.451770
\texttt{[40, 40, 40]} \texttt{[low, low, low]}      707.970055  137.606760
                      \texttt{[high, high, high]}  1256.956556  220.589856

                                                                      gap  \
model spec                                                PPO   Imitation
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           13.179568    2.544983
                      \texttt{[high, high]}         14.793097    4.163919
\texttt{[40, 40]}     \texttt{[low, low]}           28.468205    0.683903
                      \texttt{[high, high]}         42.366348    3.048982
\texttt{[60, 60]}     \texttt{[low, low]}           41.916108    1.096821
                      \texttt{[high, high]}         63.889047    1.016186
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      75.491915  493.408266
                      \texttt{[high, high, high]}  118.609136  377.317792
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     222.078030  454.534836
                      \texttt{[high, high, high]}  430.904077  504.853057

                                                                          \
model spec                                              Grid         PPO
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           2.884604    5.115436
                      \texttt{[high, high]}         1.392894    4.870032
\texttt{[40, 40]}     \texttt{[low, low]}           0.633102    3.871989
                      \texttt{[high, high]}         1.911024    6.604469
\texttt{[60, 60]}     \texttt{[low, low]}           1.656842    4.579620
                      \texttt{[high, high]}         0.306890    5.548755
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     10.784477   31.343091
                      \texttt{[high, high, high]}   2.625906   47.630185
\texttt{[40, 40, 40]} \texttt{[low, low, low]}      7.783855   73.948040
                      \texttt{[high, high, high]}   6.148815  107.352949

                                                   time train             \
model spec                                          Imitation       Grid
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           10.794131   6.528680
                      \texttt{[high, high]}         10.303269   6.367270
\texttt{[40, 40]}     \texttt{[low, low]}           13.358776  11.936231
                      \texttt{[high, high]}         24.115678  11.753293
\texttt{[60, 60]}     \texttt{[low, low]}           16.987021  18.033775
                      \texttt{[high, high]}         39.432054  17.764387
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     166.979335  10.956625
                      \texttt{[high, high, high]}  199.548570  10.584291
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     523.053128  21.516230
                      \texttt{[high, high, high]}  948.414813  20.403130


model spec                                                PPO
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}          147.328267
                      \texttt{[high, high]}        147.312099
\texttt{[40, 40]}     \texttt{[low, low]}          147.438332
                      \texttt{[high, high]}        146.418300
\texttt{[60, 60]}     \texttt{[low, low]}          147.738389
                      \texttt{[high, high]}        148.321400
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     150.058838
                      \texttt{[high, high, high]}  150.223690
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     147.643010
                      \texttt{[high, high, high]}  147.338457

In [350]:
# swap levels of MultiIndex
results.columns = results.columns.swaplevel(0, 1)
# sort columns by model first
results = results.sort_index(axis=1, level=0)
results

model spec                                              Grid              \
                                                         gap         obj
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           2.884604   12.899862
                      \texttt{[high, high]}         1.392894   14.302608
\texttt{[40, 40]}     \texttt{[low, low]}           0.633102   27.580523
                      \texttt{[high, high]}         1.911024   40.501097
\texttt{[60, 60]}     \texttt{[low, low]}           1.656842   40.744641
                      \texttt{[high, high]}         0.306890   60.716127
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     10.784477   63.675464
                      \texttt{[high, high, high]}   2.625906   82.451770
\texttt{[40, 40, 40]} \texttt{[low, low, low]}      7.783855  137.606760
                      \texttt{[high, high, high]}   6.148815  220.589856

model spec                                                                 \
                                                          opt    time opt
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           12.538185    0.494449
                      \texttt{[high, high]}         14.106125    0.482333
\texttt{[40, 40]}     \texttt{[low, low]}           27.407008    4.022383
                      \texttt{[high, high]}         39.741625    3.591624
\texttt{[60, 60]}     \texttt{[low, low]}           40.080570    5.594582
                      \texttt{[high, high]}         60.530365    9.442301
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      57.476883   18.652781
                      \texttt{[high, high, high]}   80.342063   11.573517
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     127.669176  316.696654
                      \texttt{[high, high, high]}  207.811888  307.539822

model spec                                                     Imitation  \
                                                  time train         gap
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           6.528680    2.544983
                      \texttt{[high, high]}         6.367270    4.163919
\texttt{[40, 40]}     \texttt{[low, low]}          11.936231    0.683903
                      \texttt{[high, high]}        11.753293    3.048982
\texttt{[60, 60]}     \texttt{[low, low]}          18.033775    1.096821
                      \texttt{[high, high]}        17.764387    1.016186
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     10.956625  493.408266
                      \texttt{[high, high, high]}  10.584291  377.317792
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     21.516230  454.534836
                      \texttt{[high, high, high]}  20.403130  504.853057

model spec                                                                  \
                                                           obj         opt
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}            12.857279   12.538185
                      \texttt{[high, high]}          14.693492   14.106125
\texttt{[40, 40]}     \texttt{[low, low]}            27.594446   27.407008
                      \texttt{[high, high]}          40.953340   39.741625
\texttt{[60, 60]}     \texttt{[low, low]}            40.520182   40.080570
                      \texttt{[high, high]}          61.145466   60.530365
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      341.072574   57.476883
                      \texttt{[high, high, high]}   383.486959   80.342063
\texttt{[40, 40, 40]} \texttt{[low, low, low]}      707.970055  127.669176
                      \texttt{[high, high, high]}  1256.956556  207.811888

model spec                                                                 \
                                                     time opt  time train
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}            0.494449   10.794131
                      \texttt{[high, high]}          0.482333   10.303269
\texttt{[40, 40]}     \texttt{[low, low]}            4.022383   13.358776
                      \texttt{[high, high]}          3.591624   24.115678
\texttt{[60, 60]}     \texttt{[low, low]}            5.594582   16.987021
                      \texttt{[high, high]}          9.442301   39.432054
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      18.652781  166.979335
                      \texttt{[high, high, high]}   11.573517  199.548570
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     316.696654  523.053128
                      \texttt{[high, high, high]}  307.539822  948.414813

model spec                                                PPO              \
                                                          gap         obj
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}            5.115436   13.179568
                      \texttt{[high, high]}          4.870032   14.793097
\texttt{[40, 40]}     \texttt{[low, low]}            3.871989   28.468205
                      \texttt{[high, high]}          6.604469   42.366348
\texttt{[60, 60]}     \texttt{[low, low]}            4.579620   41.916108
                      \texttt{[high, high]}          5.548755   63.889047
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      31.343091   75.491915
                      \texttt{[high, high, high]}   47.630185  118.609136
\texttt{[40, 40, 40]} \texttt{[low, low, low]}      73.948040  222.078030
                      \texttt{[high, high, high]}  107.352949  430.904077

model spec                                                                 \
                                                          opt    time opt
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           12.538185    0.494449
                      \texttt{[high, high]}         14.106125    0.482333
\texttt{[40, 40]}     \texttt{[low, low]}           27.407008    4.022383
                      \texttt{[high, high]}         39.741625    3.591624
\texttt{[60, 60]}     \texttt{[low, low]}           40.080570    5.594582
                      \texttt{[high, high]}         60.530365    9.442301
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      57.476883   18.652781
                      \texttt{[high, high, high]}   80.342063   11.573517
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     127.669176  316.696654
                      \texttt{[high, high, high]}  207.811888  307.539822

model spec
                                                   time train
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}          147.328267
                      \texttt{[high, high]}        147.312099
\texttt{[40, 40]}     \texttt{[low, low]}          147.438332
                      \texttt{[high, high]}        146.418300
\texttt{[60, 60]}     \texttt{[low, low]}          147.738389
                      \texttt{[high, high]}        148.321400
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     150.058838
                      \texttt{[high, high, high]}  150.223690
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     147.643010
                      \texttt{[high, high, high]}  147.338457

In [351]:
# collapse the 'opt' and 'time opt' columns into new top-level column
# (because these are guaranteed to be the same for every method, by construction; and caching)
top_cols_to_collapse = results.columns.get_level_values(0).unique()
sub_cols_to_collapse = ['opt', 'time opt']

# take first column per second-level (safe because values are equal)
collapsed = results[top_cols_to_collapse].T.groupby(level=1).first().T
collapsed = collapsed[sub_cols_to_collapse]

# assign a new top-level name
collapsed.columns = pd.MultiIndex.from_product([["MILP"], collapsed.columns])

# drop original columns and concatenate new column back to the original df
results = pd.concat([results.drop(columns=sub_cols_to_collapse, level=1), collapsed], axis=1)

In [352]:
# get current top-level names
top_levels = results.columns.get_level_values(0).unique()
# put MILP column first
new_order = ["MILP"] + [col for col in top_levels if col != "MILP"]
results = results.reindex(columns=new_order, level=0)

# order sub-level names
sub_level_order = ['obj', 'gap', 'time train', 'opt', 'time opt']
results = results.reindex(columns=sub_level_order, level=1)

# rename the top and bottom level
results.columns.names = ["model", "measurement"]

results

model                                                    MILP              \
measurement                                               opt    time opt
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           12.538185    0.494449
                      \texttt{[high, high]}         14.106125    0.482333
\texttt{[40, 40]}     \texttt{[low, low]}           27.407008    4.022383
                      \texttt{[high, high]}         39.741625    3.591624
\texttt{[60, 60]}     \texttt{[low, low]}           40.080570    5.594582
                      \texttt{[high, high]}         60.530365    9.442301
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      57.476883   18.652781
                      \texttt{[high, high, high]}   80.342063   11.573517
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     127.669176  316.696654
                      \texttt{[high, high, high]}  207.811888  307.539822

model                                                    Grid             \
measurement                                               obj        gap
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           12.899862   2.884604
                      \texttt{[high, high]}         14.302608   1.392894
\texttt{[40, 40]}     \texttt{[low, low]}           27.580523   0.633102
                      \texttt{[high, high]}         40.501097   1.911024
\texttt{[60, 60]}     \texttt{[low, low]}           40.744641   1.656842
                      \texttt{[high, high]}         60.716127   0.306890
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      63.675464  10.784477
                      \texttt{[high, high, high]}   82.451770   2.625906
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     137.606760   7.783855
                      \texttt{[high, high, high]}  220.589856   6.148815

model                                                           Imitation  \
measurement                                       time train          obj
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           6.528680    12.857279
                      \texttt{[high, high]}         6.367270    14.693492
\texttt{[40, 40]}     \texttt{[low, low]}          11.936231    27.594446
                      \texttt{[high, high]}        11.753293    40.953340
\texttt{[60, 60]}     \texttt{[low, low]}          18.033775    40.520182
                      \texttt{[high, high]}        17.764387    61.145466
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     10.956625   341.072574
                      \texttt{[high, high, high]}  10.584291   383.486959
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     21.516230   707.970055
                      \texttt{[high, high, high]}  20.403130  1256.956556

model                                                                      \
measurement                                               gap  time train
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}            2.544983   10.794131
                      \texttt{[high, high]}          4.163919   10.303269
\texttt{[40, 40]}     \texttt{[low, low]}            0.683903   13.358776
                      \texttt{[high, high]}          3.048982   24.115678
\texttt{[60, 60]}     \texttt{[low, low]}            1.096821   16.987021
                      \texttt{[high, high]}          1.016186   39.432054
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     493.408266  166.979335
                      \texttt{[high, high, high]}  377.317792  199.548570
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     454.534836  523.053128
                      \texttt{[high, high, high]}  504.853057  948.414813

model                                                     PPO              \
measurement                                               obj         gap
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}           13.179568    5.115436
                      \texttt{[high, high]}         14.793097    4.870032
\texttt{[40, 40]}     \texttt{[low, low]}           28.468205    3.871989
                      \texttt{[high, high]}         42.366348    6.604469
\texttt{[60, 60]}     \texttt{[low, low]}           41.916108    4.579620
                      \texttt{[high, high]}         63.889047    5.548755
\texttt{[20, 20, 20]} \texttt{[low, low, low]}      75.491915   31.343091
                      \texttt{[high, high, high]}  118.609136   47.630185
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     222.078030   73.948040
                      \texttt{[high, high, high]}  430.904077  107.352949

model
measurement                                        time train
n train               F train
\texttt{[20, 20]}     \texttt{[low, low]}          147.328267
                      \texttt{[high, high]}        147.312099
\texttt{[40, 40]}     \texttt{[low, low]}          147.438332
                      \texttt{[high, high]}        146.418300
\texttt{[60, 60]}     \texttt{[low, low]}          147.738389
                      \texttt{[high, high]}        148.321400
\texttt{[20, 20, 20]} \texttt{[low, low, low]}     150.058838
                      \texttt{[high, high, high]}  150.223690
\texttt{[40, 40, 40]} \texttt{[low, low, low]}     147.643010
                      \texttt{[high, high, high]}  147.338457

In [353]:
# further index and column renaming to taste
results.rename(columns={
    'time opt':  r'$T$',
    'time train': r'$T_\text{train}$',
    'n train': r'$n_r$',
    'F train': r'$F_\text{train}',
}, inplace=True)
results.index.rename([r'$n_r$', r'$F_\text{train}$'], inplace=True)

In [354]:
# convert to gaps strings
cols_x = results.columns.get_level_values(1) == 'gap'
results = results.astype({ col: str for col in results.columns[cols_x] })

def bold_min_sublevel(row):
    new_row = row.copy()
    cols_x = row.index.get_level_values(1) == 'gap'
    # find min among these columns
    min_val = row[cols_x].astype(float).min()
    # apply bold only to min in that sublevel
    new_row[cols_x] = [f"\\textbf{{{float(v):.2f}}}\\%" if float(v)==min_val else f"{float(v):.2f}\\%" 
                       for v in row[cols_x]]
    return new_row

# hightlight min gap, in each row
results = results.apply(bold_min_sublevel, axis=1)

In [358]:
from single.util import format_duration

# 2-leveled columns, so apply formatting at every columns,
# e.g. (PPO1, gap), (PPO2, gap), separately
time_cols = [r'$T$', r'$T_\text{train}$']
time_cols = results.columns[results.columns.isin(time_cols, 1)]
formatters = { col: format_duration for col in time_cols }

# latex \begin{table}{...} format
column_format = 'cc|cc|ccc|ccc|ccc'
latex_table = results.to_latex(multirow=True, column_format=column_format, multicolumn_format='c',
                               escape=False, float_format="%.2f", formatters=formatters,
                               caption="Performance Table")
print(latex_table)

\begin{table}
\caption{Performance Table}
\begin{tabular}{cc|cc|ccc|ccc|ccc}
\toprule
 & model & \multicolumn{2}{c}{MILP} & \multicolumn{3}{c}{Grid} & \multicolumn{3}{c}{Imitation} & \multicolumn{3}{c}{PPO} \\
 & measurement & opt & $T$ & obj & gap & $T_\text{train}$ & obj & gap & $T_\text{train}$ & obj & gap & $T_\text{train}$ \\
$n_r$ & $F_\text{train}$ &  &  &  &  &  &  &  &  &  &  &  \\
\midrule
\multirow[t]{2}{*}{\texttt{[20, 20]}} & \texttt{[low, low]} & 12.54 & (0s) & 12.90 & 2.88\% & (7s) & 12.86 & \textbf{2.54}\% & (11s) & 13.18 & 5.12\% & (2m) \\
 & \texttt{[high, high]} & 14.11 & (0s) & 14.30 & \textbf{1.39}\% & (6s) & 14.69 & 4.16\% & (10s) & 14.79 & 4.87\% & (2m) \\
\cline{1-13}
\multirow[t]{2}{*}{\texttt{[40, 40]}} & \texttt{[low, low]} & 27.41 & (4s) & 27.58 & \textbf{0.63}\% & (12s) & 27.59 & 0.68\% & (13s) & 28.47 & 3.87\% & (2m) \\
 & \texttt{[high, high]} & 39.74 & (4s) & 40.50 & \textbf{1.91}\% & (12s) & 40.95 & 3.05\% & (24s) & 42.37 & 6.60\% & (2m) \\
\cline{1-13}
\multirow[t]{2}{*}{\texttt{[60, 60]}} & \texttt{[low, low]} & 40.08 & (6s) & 40.74 & 1.66\% & (18s) & 40.52 & \textbf{1.10}\% & (17s) & 41.92 & 4.58\% & (2m) \\
 & \texttt{[high, high]} & 60.53 & (9s) & 60.72 & \textbf{0.31}\% & (18s) & 61.15 & 1.02\% & (39s) & 63.89 & 5.55\% & (2m) \\
\cline{1-13}
\multirow[t]{2}{*}{\texttt{[20, 20, 20]}} & \texttt{[low, low, low]} & 57.48 & (19s) & 63.68 & \textbf{10.78}\% & (11s) & 341.07 & 493.41\% & (3m) & 75.49 & 31.34\% & (2m) \\
 & \texttt{[high, high, high]} & 80.34 & (12s) & 82.45 & \textbf{2.63}\% & (11s) & 383.49 & 377.32\% & (3m) & 118.61 & 47.63\% & (2m) \\
\cline{1-13}
\multirow[t]{2}{*}{\texttt{[40, 40, 40]}} & \texttt{[low, low, low]} & 127.67 & (5m) & 137.61 & \textbf{7.78}\% & (22s) & 707.97 & 454.53\% & (9m) & 222.08 & 73.95\% & (2m) \\
 & \texttt{[high, high, high]} & 207.81 & (5m) & 220.59 & \textbf{6.15}\% & (20s) & 1256.96 & 504.85\% & (16m) & 430.90 & 107.35\% & (2m) \\
\cline{1-13}
\bottomrule
\end{tabular}
\end{table}

In [359]:
import re

# some further automated formatting (just search/replace)
# 1. remove all \cline
latex_table = re.sub(r'\\cline\{.*?\}\s*\n?', '', latex_table)
# 2. remove \toprule
latex_table = re.sub(r'\\toprule\s*\n?', '', latex_table)
# 3. replace \bottomrule with \midrule
latex_table = re.sub(r'\\bottomrule\s*\n?', '\\\\midrule\n', latex_table)
# 4. TODO: extract tabular
# latex_table = re.sub()
match = re.search(r"\\begin\{tabular.*?\\end\{tabular\}", latex_table, re.DOTALL)
latex_table = match.group(0)

# write complete latex template for preview
# (with timestamp)
from datetime import datetime
now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
date_line = f"\\noindent\\textit{{Compiled on: {now}}}\\\\\n"
latex = f"""
\\documentclass{{article}}
\\usepackage{{booktabs}}
\\usepackage{{multirow}}
\\usepackage{{siunitx}}
\\usepackage[skip=10pt]{{caption}}
\\usepackage[margin=1cm]{{geometry}}
\\begin{{document}}
\\begin{{table}}
{latex_table}
\\end{{table}}
{date_line}
\\end{{document}}"""

file_prefix = 'results/experiments'

with open(file_prefix + '.preview.tex', 'w') as f:
    f.write(latex)
!tectonic {file_prefix + '.preview.tex'}

Running TeX ...
warning: experiments.preview.tex:27: Overfull \hbox (74.89816pt too wide) in paragraph at lines 10--27
warning: experiments.preview.tex:29: Underfull \hbox (badness 10000) in paragraph at lines 28--29
Rerunning TeX because "experiments.preview.aux" changed ...
warning: experiments.preview.tex:27: Overfull \hbox (74.89816pt too wide) in paragraph at lines 10--27
warning: experiments.preview.tex:29: Underfull \hbox (badness 10000) in paragraph at lines 28--29
warning: warnings were issued by the TeX engine; use --print and/or --keep-logs for details.
Running xdvipdfmx ...
Writing `results/experiments.preview.pdf` (19.83 KiB)
Skipped writing 1 intermediate files (use --keep-intermediates to keep them)

In [360]:
# write only table, for direct use in report
with open(file_prefix + '.tex', 'w') as f:
    f.write(latex_table)